### ISSUE TITLE
Heroku build fails after last PR

### ISSUE THREAD

**Issue by atlj** [atlj/codenamebruh#6]
> Executing task: yarn run push <
> 
> yarn run v1.22.10
> warning ..\..\..\package.json: No license field
> $ git push heroku master
> Enumerating objects: 67, done.
> Counting objects: 100% (67/67), done.
> Delta compression using up to 4 threads
> Compressing objects: 100% (46/46), done.
> Writing objects: 100% (51/51), 5.98 KiB | 612.00 KiB/s, done.
> Total 51 (delta 32), reused 0 (delta 0)
> remote: Compressing source files... done.
> remote: Building source:
> remote: 
> remote: -----> Building on the Heroku-20 stack
> remote: -----> Node.js app detected
> remote:        
> remote: -----> Creating runtime environment
> remote:        
> remote:        NPM_CONFIG_LOGLEVEL=error
> remote:        USE_YARN_CACHE=true
> remote:        NODE_TLS_REJECT_UNAUTHORIZED=0
> remote:        NODE_VERBOSE=false
> remote:        NODE_ENV=production
> remote:        NODE_MODULES_CACHE=true
> remote:
> remote: -----> Installing binaries
> remote:        engines.node (package.json):  unspecified
> remote:        engines.npm (package.json):   unspecified (use default)
> remote:        engines.yarn (package.json):  unspecified (use default)
> remote:
> remote:        Resolving node version 12.x...
> remote:        Downloading and installing node 12.20.1...
> remote:        Using default npm version: 6.14.10
> remote:        Resolving yarn version 1.22.x...
> remote:        Downloading and installing yarn (1.22.10)
> remote:        Installed yarn 1.22.10
> remote:        
> remote: -----> Restoring cache
> remote:        - yarn cache
> remote:        
> remote: -----> Installing dependencies
> remote:        Installing node modules (yarn.lock)
> remote:        yarn install v1.22.10
> remote:        [1/4] Resolving packages...
> remote:        [2/4] Fetching packages...
> remote:        (node:569) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable 
> to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.  
> remote:        info fsevents@2.3.1: The platform "linux" is incompatible with this module.       
> remote:        info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
> remote:        [3/4] Linking dependencies...
> remote:        [4/4] Building fresh packages...
> remote:        $ tsc
 > remote:        src/modules/Replier.ts(1,53): error TS2307: Cannot find module '@/utils/Constants' or its corresponding type declarations.
> remote:        error Command failed with exit code 2.
> remote:        info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> remote: 
> remote: -----> Build failed
> remote:        
> remote:        We're sorry this build is failing! You can troubleshoot common issues here:       
> remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
> remote:
> remote:        Some possible problems:
> remote:
> remote:        - Node version not specified in package.json
> remote:          https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
> remote:
> remote:        - A module may be missing from 'dependencies' in package.json
> remote:          https://devcenter.heroku.com/articles/troubleshooting-node-deploys#ensure-you-aren-t-relying-on-untracked-dependencies
> remote:
> remote:        Love,
> remote:        Heroku
> remote:
> remote:  !     Push rejected, failed to compile Node.js app.
> remote: 
> remote:  !     Push failed
> remote: Verifying deploy...
> remote:
> remote: !       Push rejected to codenamebruh.
> remote:
> To https://git.heroku.com/codenamebruh.git
>  ! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'https://git.heroku.com/codenamebruh.git'
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> The terminal process "C:\WINDOWS\System32\cmd.exe /d /c yarn run push" terminated with exit code:

**Comment by atlj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [herokuya deploylayamıyoruz](https://trello.com/c/8d5ASbDe/16-herokuya-deploylayam%C4%B1yoruz)

**Comment by bufgix** [comment]
Batiyo muyuz kaptan

**Comment by bufgix** [comment]
Bakacam eve geçince

**Comment by atlj** [comment]
O7

**Comment by atlj** [comment]
@bufgix so far no good
flag ile yapılan denemelerin hepsinde aynı hataları aldım.

**Denediğim flagler:**

> YARN_PRODUCTION=false
> NPM_CONFIG_PRODUCTION=false
> NODE_ENV=development

**Comment by bufgix** [comment]
`module_alias` paketini devDep den normal deps e tasisana @atlj

**Comment by atlj** [comment]
TODO
